### ISSUE TITLE
Append logic inverted

### ISSUE THREAD

**Issue by tristandostaler** [OkiokData/SmartHashCat#11]
Not sure how it happened, but the Append logic is inverted in the function send_content_to_file

    def send_content_to_file(self, command, content, file_out, append=True):
        if append:
            CommandRunner.run_command(command + " " + content + " > " +
                                      file_out, silent=False)
        else:
            CommandRunner.run_command(command + " " + content + " >> " +
                                      file_out, silent=False)

Shoulkd be if not append:

**Comment by tristandostaler** [comment]
Fyi i fixed this in my PR with the new architecture

**Comment by mlahaye811** [comment]
Fixed in master
