### ISSUE TITLE
Problem with rockyou file

### ISSUE THREAD

**Issue by tristandostaler** [OkiokData/SmartHashCat#2]
SHC assumes the rockyou file is in /usr/share/wordlists/rockyou.txt and the setup.sh file installs it in usr/share/SmartHashCat/lists.
So we need to either:
1. CHange SHC to fetch rockyou at the new location
2. Or modify the setup.sh
3. Or (and it might be the best option) tell SHC to check both places.

**Comment by tristandostaler** [comment]
I will start fixing it using option no3 and assume the downloaded rockyou file is the best option between the 2

**Comment by tristandostaler** [comment]
#5 Fixed in PR

**Comment by mlahaye811** [comment]
Updated setup.sh to handle existing rockyou database in wordlists.
