### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by tristandostaler** [OkiokData/SmartHashCat#3]
I noticed a few bugs in the functionning of SHC:
1. In SHC.py -> usage = '''' -> has 1 too many ' and then outputs ' in the usage:
usage: '
    smarthashcat -p <attack phase number>     [arguments needed for the choosen phase]    

2. at the moment the -f option is mandatory so it's not possible to do --clear without specifying the -f argument (which is ironic)

If I find more, i'll report them here

**Comment by tristandostaler** [comment]
#6 fixed both in PR

**Comment by tristandostaler** [comment]
#7 fixed in PR. Also isolated from bug No2

**Comment by mlahaye811** [comment]
Merged.
